{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toefl-evaluator.fullname" . }}-secrets
  labels:
    {{- include "toefl-evaluator.labels" . | nindent 4 }}
type: Opaque
stringData:
  clova-secret-key: {{ .Values.secrets.clovaSecretKey | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | quote }}
{{- end }}
